In [7]:
!pip install scikit-multiflow --q

You should consider upgrading via the '/home/ec2-user/anaconda3/envs/tensorflow_p36/bin/python -m pip install --upgrade pip' command.


In [10]:
import tensorflow as tf
import keras
import numpy as np
from skmultiflow.data import SEAGenerator as sea

import warnings
warnings.filterwarnings("ignore")

In [70]:
from keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train  = X_train / 255
X_test  = X_test / 255
num_pixels = X_train.shape[1] * X_train.shape[2]

y_new = np.zeros(y_train.shape)
y_new[np.where(y_train==5.0)[0]] = 1
y_train = y_new

y_new = np.zeros(y_test.shape)
y_new[np.where(y_test==5.0)[0]] = 1
y_test = y_new

y_train = keras.utils.to_categorical(y_train)
y_test = keras.utils.to_categorical(y_test)

In [71]:
X_train.shape

(60000, 28, 28)

In [87]:
y_train.shape

(10000, 2)

In [73]:
y_train

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [12]:
generator = sea()

In [14]:
generator.next_sample()

(array([[2.60248935, 8.60105808, 4.38771832]]), array([1]))

In [88]:
from keras.models import Sequential
from keras.layers import Dense, Flatten

num_classes = 2
num_h = 3

model = Sequential()
model.add(Flatten(input_shape=(X_train.shape[1], X_train.shape[2])))
d = Dense(num_h, activation='relu', kernel_initializer='normal')#, input_shape=(1, 3))
model.add(d)
model.add(Dense(num_classes, activation='softmax', kernel_initializer='normal'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_2 (Flatten)          (None, 3)                 0         
_________________________________________________________________
dense_11 (Dense)             (None, 3)                 12        
_________________________________________________________________
dense_12 (Dense)             (None, 2)                 8         
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________


In [43]:
model.trainable_weights

[<tf.Variable 'dense_7/kernel:0' shape=(3, 1) dtype=float32_ref>,
 <tf.Variable 'dense_7/bias:0' shape=(1,) dtype=float32_ref>,
 <tf.Variable 'dense_8/kernel:0' shape=(1, 2) dtype=float32_ref>,
 <tf.Variable 'dense_8/bias:0' shape=(2,) dtype=float32_ref>]

In [57]:
import pandas as pd

In [79]:
def buid_set(size, generator):
    X, Y = [], []
    for i in range(size):
        x, y = generator.next_sample()
        X.append(x)
        Y.append(float(y[0]))
    Y = pd.get_dummies(pd.Series(Y)).to_numpy()
    return np.array(X), np.array(Y)

In [80]:
X_train, y_train = buid_set(10000, generator)
X_test, y_test = buid_set(1000, generator)

In [81]:
y_train

array([[0, 1],
       [0, 1],
       [1, 0],
       ...,
       [0, 1],
       [1, 0],
       [1, 0]], dtype=uint8)

In [82]:
y_train.shape

(10000, 2)

In [83]:
X_train.shape

(10000, 1, 3)

In [89]:
epochs = 3
batch_size = 128
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=epochs, batch_size=batch_size)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Train on 10000 samples, validate on 1000 samples
Epoch 1/3





10000/10000 [==============================] - 2s 185us/step - loss: 0.6261 - acc: 0.6729 - val_loss: 0.5477 - val_acc: 0.6810
Epoch 2/3
10000/10000 [==============================] - 0s 16us/step - loss: 0.5144 - acc: 0.6770 - val_loss: 0.4792 - val_acc: 0.6810
Epoch 3/3
10000/10000 [==============================] - 0s 16us/step - loss: 0.4514 - acc: 0.7037 - val_loss: 0.4244 - val_acc: 0.7470


In [5]:
after = d.get_weights()

In [8]:
d.trainable = False

In [9]:
model1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [10]:
model1.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 785       
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 4         
Total params: 789
Trainable params: 4
Non-trainable params: 785
_________________________________________________________________


In [12]:
epochs = 2
batch_size = 128
model1.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=epochs, batch_size=batch_size)

Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 2s 36us/step - loss: 0.1084 - acc: 0.9680 - val_loss: 0.1012 - val_acc: 0.9711
Epoch 2/2
60000/60000 [==============================] - 1s 23us/step - loss: 0.1035 - acc: 0.9683 - val_loss: 0.0986 - val_acc: 0.9714


In [13]:
after_3= d.get_weights()

In [32]:
d.trainable = True
print(model1.trainable_weights)

epochs = 6
batch_size = 128
model1.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=epochs, batch_size=batch_size)

[<tf.Variable 'dense_1/kernel:0' shape=(784, 1) dtype=float32_ref>, <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32_ref>, <tf.Variable 'dense_2/kernel:0' shape=(1, 2) dtype=float32_ref>, <tf.Variable 'dense_2/bias:0' shape=(2,) dtype=float32_ref>]
Train on 60000 samples, validate on 10000 samples
Epoch 1/6
60000/60000 [==============================] - 1s 22us/step - loss: 0.0981 - acc: 0.9718 - val_loss: 0.0926 - val_acc: 0.9733
Epoch 2/6
60000/60000 [==============================] - 1s 22us/step - loss: 0.0944 - acc: 0.9728 - val_loss: 0.0917 - val_acc: 0.9726
Epoch 3/6
60000/60000 [==============================] - 1s 22us/step - loss: 0.0917 - acc: 0.9736 - val_loss: 0.0884 - val_acc: 0.9747
Epoch 4/6
60000/60000 [==============================] - 1s 22us/step - loss: 0.0899 - acc: 0.9739 - val_loss: 0.0888 - val_acc: 0.9752
Epoch 5/6
60000/60000 [==============================] - 1s 22us/step - loss: 0.0888 - acc: 0.9743 - val_loss: 0.0881 - val_acc: 0.9756
Epoch 6/6
60000

In [16]:
after[0] == after_3[0]

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [

In [18]:
after[0][0:20]

array([[ 0.04466002],
       [ 0.04611144],
       [ 0.03130344],
       [-0.03725884],
       [ 0.01148854],
       [ 0.00646817],
       [-0.01815568],
       [ 0.00515334],
       [-0.02820878],
       [ 0.01650673],
       [-0.01893103],
       [-0.0122538 ],
       [-0.05547793],
       [ 0.07850227],
       [-0.03446824],
       [ 0.08233008],
       [-0.07949447],
       [-0.02539072],
       [ 0.05617425],
       [ 0.04319464]], dtype=float32)

In [29]:
assert list(after[0]) == list(after_2[0])

AssertionError: 

[array([0.04466002], dtype=float32),
 array([0.04611144], dtype=float32),
 array([0.03130344], dtype=float32),
 array([-0.03725884], dtype=float32),
 array([0.01148854], dtype=float32),
 array([0.00646817], dtype=float32),
 array([-0.01815568], dtype=float32),
 array([0.00515334], dtype=float32),
 array([-0.02820878], dtype=float32),
 array([0.01650673], dtype=float32),
 array([-0.01893103], dtype=float32),
 array([-0.0122538], dtype=float32),
 array([-0.05547793], dtype=float32),
 array([0.07850227], dtype=float32),
 array([-0.03446824], dtype=float32),
 array([0.08233008], dtype=float32),
 array([-0.07949447], dtype=float32),
 array([-0.02539072], dtype=float32),
 array([0.05617425], dtype=float32),
 array([0.04319464], dtype=float32),
 array([-0.07760277], dtype=float32),
 array([0.02190755], dtype=float32),
 array([-0.03760276], dtype=float32),
 array([-0.01174445], dtype=float32),
 array([0.00916482], dtype=float32),
 array([0.05696033], dtype=float32),
 array([0.00075774], dtype=

In [25]:
after[0][0:20]

array([[-0.09059402],
       [ 0.08287834],
       [ 0.02098129],
       [ 0.04530345],
       [ 0.01122736],
       [-0.00822759],
       [ 0.05490516],
       [ 0.13641195],
       [-0.00852195],
       [ 0.02560031],
       [-0.13766341],
       [-0.03244513],
       [ 0.13771065],
       [ 0.06318931],
       [-0.00753731],
       [ 0.03811729],
       [-0.05365614],
       [ 0.05068101],
       [-0.0129208 ],
       [-0.05633954]], dtype=float32)

In [15]:
l = model1.trainable_weights[0]

In [27]:
model1.trainable_weights

[<tf.Variable 'dense_2/kernel:0' shape=(1, 2) dtype=float32_ref>,
 <tf.Variable 'dense_2/bias:0' shape=(2,) dtype=float32_ref>]

False

In [19]:
l.graph

In [20]:
l.initial_value

<tf.Tensor 'dense_5/random_normal:0' shape=(784, 1) dtype=float32>

In [23]:
print(l)

<tf.Variable 'dense_5/kernel:0' shape=(784, 1) dtype=float32_ref>


In [22]:
?l.read_value

Signature: l.read_value()
Docstring:
Returns the value of this variable, read in the current context.

Can be different from value() if it's on another device, with control
dependencies, etc.

Returns:
  A `Tensor` containing the value of the variable.
File:      ~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py
Type:      method


In [ ]:
l.